<Project Sdk="Microsoft.NET.Sdk">
    <Import Condition="Exists('LocalConfig.props')" Project="LocalConfig.props"/>

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <AssemblyTitle>HornetPlayer</AssemblyTitle>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <DebugType>portable</DebugType>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisMode>recommended</AnalysisMode>

        <!-- Shortens and anonymizes paths in debug symbols relative to the project directory. Breakpoints will not work, however. -->
        <PathMap Condition="'$(Configuration)' == 'Release'">$(MSBuildProjectDirectory)=/</PathMap>

        <!-- todo macOS -->
        <GamePath Condition="'$(GamePath)' == '' And '$(OS)' == 'Windows_NT'">C:/Program Files (x86)/Steam/steamapps/common/Hollow Knight</GamePath>
        <GamePath Condition="'$(GamePath)' == '' And '$(OS)' != 'Windows_NT'">$(HOME)/.local/share/Steam/steamapps/common/Hollow Knight</GamePath>
        <HollowKnightRefs>$(GamePath)/hollow_knight_Data/Managed</HollowKnightRefs>

        <CopyDir Condition="'$(CopyDir)' == ''">$(HollowKnightRefs)/Mods/HornetPlayer</CopyDir>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.26.0" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Game/engine assemblies are provided at runtime, so don't copy them into the Mods folder (Private=false). -->
        <Reference Include="Assembly-CSharp" Private="false">
            <HintPath>$(HollowKnightRefs)/Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="TeamCherry.TK2D" Private="false">
            <HintPath>$(HollowKnightRefs)/TeamCherry.TK2D.dll</HintPath>
        </Reference>
        <Reference Include="TeamCherry.SharedUtils" Private="false">
            <HintPath>$(HollowKnightRefs)/TeamCherry.SharedUtils.dll</HintPath>
        </Reference>
        <Reference Include="TeamCherry.NestedFadeGroup" Private="false">
            <HintPath>$(HollowKnightRefs)/TeamCherry.NestedFadeGroup.dll</HintPath>
        </Reference>
        <Reference Include="PlayMaker" Private="false">
            <HintPath>$(HollowKnightRefs)/PlayMaker.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Physics2DModule" Private="false">
            <HintPath>$(HollowKnightRefs)/UnityEngine.Physics2DModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AudioModule" Private="false">
            <HintPath>$(HollowKnightRefs)/UnityEngine.AudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ParticleSystemModule" Private="false">
            <HintPath>$(HollowKnightRefs)/UnityEngine.ParticleSystemModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine" Private="false">
            <HintPath>$(HollowKnightRefs)/UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule" Private="false">
            <HintPath>$(HollowKnightRefs)/UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule" Private="false">
            <HintPath>$(HollowKnightRefs)/UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ScreenCaptureModule" Private="false">
            <HintPath>$(HollowKnightRefs)/UnityEngine.ScreenCaptureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule" Private="false">
            <HintPath>$(HollowKnightRefs)/UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json" Private="false">
            <HintPath>$(HollowKnightRefs)/Newtonsoft.Json.dll</HintPath>
        </Reference>
    </ItemGroup>

    <Target Name="CopyMod" AfterTargets="PostBuildEvent" Condition="'$(CopyDir)' != ''">
        <Message Importance="high" Text="copying $(TargetPath) to $(CopyDir) ..."/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(CopyDir)" SkipUnchangedFiles="true"/>
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(CopyDir)" SkipUnchangedFiles="true"/>
    </Target>
</Project>
