# Asset repacking based on rabex
[package]
name = "hornet-asset-pipeline"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rabex = { version = "0.1", default-features = false, features = ["embed-tpk"] }
rabex-env = { git = "https://github.com/jakobhellermann/rabex-env.git", rev = "6a3ba4ea8e6d506bb04a24ecd78c4bf7619b7b86" }
anyhow = "1.0"
rustc-hash = "2.1"
steamlocate = "2.0"

[[bin]]
name = "remap-monoscripts"
path = "src/bin/remap-monoscripts.rs"

[[bin]]
name = "repack-resources"
path = "src/bin/repack-resources.rs"
